### ISSUE TITLE
Would it be possible to list price history?

### ISSUE THREAD

**Issue by 0507spc** [fedecalendino/app-info-bot#1]
I have a shortcut that does this, but this seems like a more practical way of doing it.

Reason is, some devs have a price 0.99 and regularly hike the price for a few days and then discount back to what is really the actual price.

happy to share the shortcut if that helps (uses appsliced).

love the bot!

**Comment by fedecalendino** [comment]
Ohh interesting idea. I'd like to take a look to that shortcut :)

**Comment by 0507spc** [comment]
It’s nothing fancy, but does the job, displaying the history in a notification.

https://www.icloud.com/shortcuts/f2370757f9d843c180cd3c5d4f9fe882

I don’t know python, but can usually infer enough, so if I can help I will.

was thinking something like the last 3 price changes and lowest it has been.

**Comment by fedecalendino** [comment]
@0507spc done! check out the latests posts in /r/apphookup :)

**Comment by 0507spc** [comment]
That's excellent work. Thanks for implementing it, looks great.
